# Generated by Django 4.1.7 on 2023-04-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=100)),
                ('year_of_manufacture', models.IntegerField()),
                ('number_of_seats', models.IntegerField()),
                ('body_type', models.CharField(max_length=100)),
                ('engine_capacity', models.FloatField()),
            ],
        ),
    ]
